version: "2.0"
services:
  octapi-worker:
    build: ./
    ports:
    - "22:22"
    network_mode: host
    container_name: octapi-worker
    privileged: true
  # Add Node Exporter to this app    
  node_exporter:
    build: ./node_exporter
    ports:
      - "9100:9100"
    network_mode: host
    container_name: node_exporter