version: "2.0"
services:
  octapi-worker:
    build: ./
    network_mode: host
    container_name: octapi-worker
    privileged: true
  # Add Node Exporter to this app    
  node_exporter:
    build: ./node_exporter
    network_mode: host
    container_name: node_exporter